from __future__ import annotations

import argparse
import json
from pathlib import Path


def render_markdown(report: dict) -> str:
    metrics = report.get("metrics", {})
    latency = metrics.get("latency_seconds", {})
    return "\n".join(
        [
            "# Emotion Media Dashboard",
            "",
            "## KPI",
            f"- Samples: `{metrics.get('count', 0)}`",
            f"- p50 latency: `{latency.get('p50', 0)}s`",
            f"- p95 latency: `{latency.get('p95', 0)}s`",
            f"- Mean latency: `{latency.get('mean', 0)}s`",
            f"- Fallback rate: `{metrics.get('fallback_rate', 0)}`",
            f"- Quality pass rate: `{metrics.get('quality_pass_rate', 0)}`",
            f"- Emotion accuracy: `{metrics.get('emotion_accuracy', 'n/a')}`",
            "",
            "## Notes",
            "- Use this file for quick trend checks in CI artifacts.",
            "- Pair with the JSON report for deeper per-sample analysis.",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Render markdown dashboard from evaluation report")
    parser.add_argument("--report", required=True, help="Path to report.json generated by evaluation script")
    parser.add_argument("--output", default="outputs/emotion_media_eval/dashboard.md", help="Output markdown path")
    args = parser.parse_args()

    report_path = Path(args.report)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    report = json.loads(report_path.read_text(encoding="utf-8"))
    markdown = render_markdown(report)
    output_path.write_text(markdown, encoding="utf-8")
    print(f"Wrote dashboard markdown to {output_path}")


if __name__ == "__main__":
    main()
